version: "3.8"

services:
  pypi-server:
    image: pypiserver/pypiserver:v1.5.2
    container_name: pypiserver
    volumes:
      - /volume1/docker/pypiserver/packages:/data/packages
    command: -P . -a . /data/packages
    restart: always
    user: "1000:1000"
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - homeserver
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - my.zone=homeserver
      - traefik.enable=true
      - traefik.http.routers.pypiserver.rule=Host(`pypi.${SERVER_DOMAIN}`)
      - traefik.http.routers.pypiserver.entrypoints=websecure
      - traefik.http.routers.pypiserver.tls.certresolver=myresolver
      - traefik.http.services.pypiserver.loadbalancer.server.port=8080
      - traefik.docker.network=homeserver

networks:
  homeserver:
    name: homeserver
    external: true